### ISSUE TITLE
Descriptive Registration Exception Information

### ISSUE THREAD

**Issue by vector-man** [z4kn4fein/stashbox#10]
It would be nice if exceptions during registration contained descriptive information, so it is easy to find out what mistake you made: 

e.g: Resolve failed for a particular registration (forgot to register it). Exception message contains the exact constructor that was affected and which parameter/type. Autofac, for example, handles this pretty well.

**Comment by z4kn4fein** [comment]
Thanks for the feedback, i'll change the behavior more like that!

**Comment by z4kn4fein** [comment]
Hey, in the latest beta package i added more details to the exception, if you have a chance could you please try that it meets your expectations or should i add some more details?
Thanks!

**Comment by z4kn4fein** [comment]
Updated in [2.4.1](https://github.com/z4kn4fein/stashbox/releases/tag/2.4.1)
