### ISSUE TITLE
Question: Please explain Interception example a bit more.

### ISSUE THREAD

**Issue by schuettecarsten** [z4kn4fein/stashbox#110]
Please explain Interception example a bit more. I have no idea why the sample works.
https://z4kn4fein.github.io/stashbox/#/advanced/decorators?id=interception

**Comment by z4kn4fein** [comment]
Hi,

Thank you for reaching out! You are right, the interception example is not detailed enough, I'll put there a better explanation.
But let me summarize here quick how interception with Castle DynamicProxy works:

With Castle's `DefaultProxyBuilder` you can generate proxy implementation classes for interfaces. These proxy classes depend on the actual implementation of the given interface and an `IInterceptor` collection that holds the additional logic you want to be executed on each call of the interface's methods.

### A simplified example:
Here's an interface that we want to extend with additional logic.
```cs
interface IExample
{
    void DoWork();
}
```
We can generate a proxy implementation type with `DefaultProxyBuilder`:
```cs
Type exampleProxyType = proxyBuilder.CreateInterfaceProxyTypeWithTargetInterface(
    typeof(IExample), // the interface the proxy must be generated from
    new Type[0], 
    ProxyGenerationOptions.Default);
```
The generated proxy type will look something like this:
```cs
class generated_ProxyIExample : IExample 
{
    public ProxyIExample(IExample actualImplementation, IInterceptor[] interceptors)
    { /* ... */ }

    public void DoWork()
    {
        // It's calling the interceptors and the actualImplementation's DoWork() 
    }
}
```
Within the `IInterceptor` implementations, you can define the additional logic you want to get executed on the interface's method calls.
```cs
class ExampleInterceptor : IInterceptor
{ 
    public void Intercept(IInvocation invocation)
    {
        Console.WriteLine($"Before method {invocation.GetConcreteMethod().Name}");
        invocation.Proceed();
        Console.WriteLine($"After method {invocation.GetConcreteMethod().Name}");
     }
}
```
You can wire all this together so Stashbox can automatically apply the interceptors to your interfaces.
```cs
// register your actual IExample implementation.
container.Register<IExample, ActualExampleImplementation>(); 
 
// register your interceptor so Stashbox can inject it into your proxy class,
// as the proxy class depend on an IInterceptor collection, you can register more than one interceptor of course.
container.Register<IInterceptor, ExampleInterceptor>();

// register the proxy class as a decorator, so Stashbox can resolve the proxy class 
// when IExample is requested and can inject your actual implementation into it.
container.RegisterDecorator<IExample>(exampleProxyType);
```


So, this is it basically, let me know if you need more details.
