### ISSUE TITLE
Enhancement: IServiceProviderIsService

### ISSUE THREAD

**Issue by adambajguz** [z4kn4fein/stashbox#115]
Hi @z4kn4fein,
do you plan to add support for [`IServiceProviderIsService`](https://andrewlock.net/exploring-dotnet-6-part-10-new-dependency-injection-features-in-dotnet-6/#detecting-if-a-service-is-registered-in-the-di-container) (which was added in .NET 6) in `IDependencyResolver`/`StashboxContainer`?

**Comment by z4kn4fein** [comment]
Hi @adambajguz, 

`IServiceProviderIsService` is part of the `Microsoft.Extensions.DependencyInjection.Abstractions` 3rd party package and not the runtime itself like `IServiceProvider`, so it was not added to the core `Stashbox` project. However, I added it to the `Stashbox.Extensions.DependencyInjection` package [here](https://github.com/z4kn4fein/stashbox-extensions-dependencyinjection/blob/master/src/stashbox.extensions.dependencyinjection/StashboxServiceProvider.cs#L12). (This package is the foundation of each .NET core extension of Stashbox)

**Comment by adambajguz** [comment]
Oh, I didn't notice that StashboxServiceProvider implements it 🙈. Thanks!
