### ISSUE TITLE
Named resolution using ResolveAll returns all named and unnamed instanсes disregarding the WithNamedDependencyResolutionForUnNamedRequests flag 

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [z4kn4fein/stashbox#118]
Hi!
Please help me understand if this is intended or it is a bug:

When registering services named and unnamed it seems like when ResolveAll<T>(<name>)

var container = new StashboxContainer(x => x.WithNamedDependencyResolutionForUnNamedRequests(true or false));
            container.Register<IFoo, Foo>(x => x.WithName("foo1"));
            container.Register<IFoo, Foo>(x => x.WithName("foo2"));
            container.Register<IFoo, Foo>();

            var foos = container.ResolveAll<IFoo>(); // returns all 3
            var foos1 = container.ResolveAll<IFoo>("foo1"); // returns all 3 but expected only those with name "foo1" or empty collection if none found

**Comment by vladimir-ilnytskyi** [comment]
Sorry, found that it was fixed in later release!
[v5.4.0](https://github.com/z4kn4fein/stashbox/compare/5.3.0...5.4.0) - 2022-05-03

**Comment by z4kn4fein** [comment]
Hi @vladimir-ilnytskyi, it seems it's a bug, I'm going to work on the fix.

**Comment by vladimir-ilnytskyi** [comment]
@z4kn4fein thanks a lot for fast response! I've noticed also that behavior when resolved via collection of services when they were registered as 
container.Register<IBar, Bar>(x => x.WithDepedency<IFoo>("foo1"))

ctor Bar(IEnumerable<IFoo> foos)

**Comment by z4kn4fein** [comment]
Yep, that uses the same mechanism as your first example. The functionality is broken in one place that I have to find. :)

**Comment by z4kn4fein** [comment]
I've published the fix with a pre-release version `5.4.3-preview-762`, could you please try that it works as you expected? Thanks!

**Comment by vladimir-ilnytskyi** [comment]
@z4kn4fein thanks a lot for a really fast fix!
Works as expected according to unittests that you've added, but I've just also confirmed it in code.
