### ISSUE TITLE
5.5.0 breaks resolution

### ISSUE THREAD

**Issue by schuettecarsten** [z4kn4fein/stashbox#119]
I upgraded to 5.5.0 and now I get exceptions that I did not get before and that go away if I downgrade to 5.4.7.
Exception is:

```
Unable to resolve type 'DataContext'.
Constructor Void .ctor(Microsoft.Extensions.Logging.ILogger`1[DataContext], ITenantDbContextFactory`1[CmtDbContext]) found with unresolvable parameter: ITenantDbContextFactory`1[[CmtDbContext]])dbContextFactory.
```

I heavily use container.Register calls and during the last changes, something broke. At the moment, I have to time to debug this as I am about to leave for the next 12 days. The only thing that I found out Stashbox knows 1176 service registrations with 5.4.7 and - without any other changes - only 1171 services with v5.5.0

**Comment by z4kn4fein** [comment]
Hi @schuettecarsten, thanks for the report! I'm going to investigate this, could you please share some configuration details about the related services?

**Comment by z4kn4fein** [comment]
I've found an issue related to open generic registrations, but I'm not sure whether it's related to your issue or not. The fix is in `5.5.1`, please let me know if this issue is still happening.

**Comment by schuettecarsten** [comment]
I tried 5.5.1, but the exception still occurs.

I have registered an unknown type resolution handler and logged its output. It reports that it cannot resolve `ITenantDbContextFactory<CmtDbContext>` immediately before the exception is thrown. In the list of registered services, I can find two service registrations for that service:

```
ITenantDbContextFactory<CmtDbContext> -> CmtDbContextFactory
ITenantDbContextFactory<CmtDbContext,long> -> CmtDbContextFactory
```

The first one should be used here, but maybe Stashbox is not able to handle this because there is a second registration with two generic parameters?

**Comment by z4kn4fein** [comment]
Thank you for your response! 
Unfortunately, it's not the case, Stashbox differentiates between those two types, so it resolves `CmtDbContextFactory` correctly when `ITenantDbContextFactory<CmtDbContext>` is requested in that scenario. I assume the issue lies elsewhere.

Are you using any complex configurations on `ITenantDbContextFactory<CmtDbContext>` or `DataContext`?

**Comment by schuettecarsten** [comment]
It's really hard to debug and to look into the Stashbox service registrations because the ImmutableBucket implementation is not very debugger-friendly. So maybe it's a good idea to add a DebugView helper class first to be able to show all registrations in a flat list and analyze them....?

**Comment by z4kn4fein** [comment]
You can get a flat map of the registrations by calling the `container.GetRegistrationMappings()` method, it will give you key-value pairs of `Type -> ServiceRegistration`. Does this help?

**Comment by z4kn4fein** [comment]
I have added Debugger proxies for several structures in `5.5.2-preview-768`, I hope this will make the debugging easier.

**Comment by schuettecarsten** [comment]
I have done some debugging and found this behaviour. I have the following service registrations for the type `CmtDbContactFactory`:

![image](https://user-images.githubusercontent.com/1275166/195813767-68a32db5-148f-4f53-8ab5-2044f27059c5.png)

I use the `Container.Register()` method with typeFrom and typeTo set to `CmtDbContextFactory` and call `AsServiceAlso` for the four interfaces. Scope is set to singleton. This results into two service mappings:

![image](https://user-images.githubusercontent.com/1275166/195816071-daebc078-5bcb-4690-97b2-0ebd7ab27a33.png)

**Comment by z4kn4fein** [comment]
Thanks for

**Comment by z4kn4fein** [comment]
I've released `v5.5.2` with the fix, could you please verify that it works now as expected? Thanks!

**Comment by schuettecarsten** [comment]
Thank you, the issue seems to be fixed with this version.

**Comment by z4kn4fein** [comment]
Thank you for the details, it did help a lot!
