### ISSUE TITLE
Unable to resolve type 'Orleans.Serialization.Serializers.IValueSerializer`1[Orleans.Serialization.Codecs.ImmutableArraySurrogate`1[Orleans.Metadata.GrainManifest]]'

### ISSUE THREAD

**Issue by dmitrig89** [z4kn4fein/stashbox#133]
Similar to issue #132 

When running the Microsoft Orleans client, and using StashBox, I'm getting the following error:

    Unable to resolve service for type 'Orleans.Serialization.Serializers.IValueSerializer`1[Orleans.Serialization.Codecs.ImmutableArraySurrogate`1[Orleans.Metadata.GrainManifest]]' while attempting to activate 'Orleans.Serialization.Codecs.ImmutableArrayCodec`1[Orleans.Metadata.GrainManifest]'

The following packages were used:

```
Microsoft.Extensions.Hosting Version=7.0.1
Microsoft.Orleans.Client Version=7.1.1
Stashbox.Extensions.Hosting Version=4.6.1
```

To reproduce the issue, simply run an Orleans client (with or without a server running, this issue will happen anyway):

```
using Microsoft.Extensions.Hosting;

await Host.CreateDefaultBuilder(args)
    .UseStashbox()
    .UseOrleansClient(siloBuilder =>
    {
        siloBuilder.UseLocalhostClustering(); ;
    })
    .RunConsoleAsync();
```

If we run without StashBox, no such error appears:

```
using Microsoft.Extensions.Hosting;

await Host.CreateDefaultBuilder(args)
    .UseOrleansClient(siloBuilder =>
    {
        siloBuilder.UseLocalhostClustering(); ;
    })
    .RunConsoleAsync();
```

**Comment by dmitrig89** [comment]
This is happening because the `ImmutableArraySurrogate` is a struct and therefore a value type. 
It will not have a public parameterless constructor.

**Comment by z4kn4fein** [comment]
Hi @dmitrig89, thanks again for reporting!
I've fixed this in `v5.8.2`. Let me know if further issues appear!

**Comment by dmitrig89** [comment]
Thank you very much @z4kn4fein, I really appreciate your dedication and it's amazing how quickly you get issues resolved.

**Comment by z4kn4fein** [comment]
Thank you for your appreciation! :)

**Comment by dmitrig89** [comment]
Looks  good so far. 
Closing this issue.

Thanks a lot for your help @z4kn4fein
