### ISSUE TITLE
Mixture of named and non named registrations result in the wrong type resolved

### ISSUE THREAD

**Issue by Kadajski** [z4kn4fein/stashbox#35]
If I have code like this:

```StashboxContainer sb = new StashboxContainer();
sb.RegisterSingleton(typeof(ITest), typeof(Test));
sb.RegisterSingleton(typeof(ITest), typeof(Test1), "Test2");
sb.RegisterSingleton(typeof(ITest), typeof(Test2), "Test3");
var test = sb.Resolve<ITest>();
```

The result will be of type `Test2` while I would expect it to be `Test` as I'm requesting it without a name I expect to get the nameless registration. If I rearrange the ordering I always get the last registered type.

**Comment by z4kn4fein** [comment]
Hi @Kadajski 

Thanks for pointing this out, i see where the issue is, i'll fix it soon and ping back with the results.

**Comment by z4kn4fein** [comment]
Hi @Kadajski 

I fixed this issue, you can check it in the latest pre-release build [here](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox). I'll publish it with the next release, please let me know if you have further issues.
