### ISSUE TITLE
latest stashbox version (2.5.7) failing with SignalR

### ISSUE THREAD

**Issue by gattml** [z4kn4fein/stashbox#39]
I'm not sure what all information you need, but I upgraded stashbox last Friday via NuGet to v2.5.7, and since that time my project doesn't work.  It appears to be failing trying to use the OWIN SignalR container - an exception is thrown at: app.UseStashboxSignalR(container, configSignalR);  The exception is:

System.MissingMethodException was unhandled by user code
  HResult=-2146233069
  Message=Method not found: 'Stashbox.Infrastructure.IDependencyRegistrator Stashbox.DependencyRegistratorExtensions.RegisterSingleton(Stashbox.Infrastructure.IDependencyRegistrator, System.Object)'.
  Source=Stashbox.AspNet.SignalR.Owin
  StackTrace:
       at Stashbox.Infrastructure.AppBuilderSignalRExtensions.AddOwinSignalR(IStashboxContainer container, HubConfiguration config, Assembly[] assemblies)
       at Owin.AppBuilderSignalRExtensions.UseStashboxSignalR(IAppBuilder app, IStashboxContainer container, HubConfiguration config, Assembly[] assemblies)
       at MyApi.Startup.Configuration(IAppBuilder app) in D:\dev\MyProject\MyApi\App_Start\Startup.cs:line 92
  InnerException: 

My project is a VS2015 Web Api and SignalR project.

Everything was working perfectly with v2.5.6.

Is there something I can do to fix this?  What are the options?  Do you need any more info?

Thank you.

**Comment by z4kn4fein** [comment]
Hi @gattml 

Thank you for posting this issue, there was an interface reconstruction in the core package, that is why you are getting this error, i had to recompile the extension libraries with the modified interface. I already published them to nuget, they are using the current 2.5.7 stashbox version now. Updating to them should eliminate this issue, could you please also confirm that it's working again?

Thanks!

**Comment by gattml** [comment]
Hello @z4kn4fein...I guess I saw and posted the issue a few hours before you fixed it and released the updates.  After upgrading the extension libraries, everything is working again.  I guess we can close out this issue.  Thank you so much!

**Comment by z4kn4fein** [comment]
Cool, happy to hear that!
Thanks!
