### ISSUE TITLE
Circular dependency tracking doesn't work with factory resolution

### ISSUE THREAD

**Issue by Kadajski** [z4kn4fein/stashbox#42]
I'm not too sure if this is by-design or not. Though this following code causes a stackoverflow
```
public interface IFoo
{
}
public class Foo : IFoo
{
    public Foo(IFoo foo)
    {

    }
}
```
```
var container = new StashboxContainer(configurator => configurator.WithCircularDependencyTracking());
container.RegisterType<IFoo, Foo>(registrator => registrator.WithFactory(() => new Foo(container.Resolve<IFoo>())));
container.Resolve<IFoo>();
```

The circular dependency tracking works fine if I remove the "WithFactory" bit.

**Comment by z4kn4fein** [comment]
Hi @Kadajski 
Thank you for pointing this out, i'll check it soon!

**Comment by Kadajski** [comment]
hey, this was causing issues I suspect as I have a large codebase that I was trying to switch over to stashbox and it was crashing in production. These issues are fairly difficult to track down though as I couldn't find the issue in dev. So this would definitely be a useful feature to have. I will try and find the issue in my codebase though. Thanks anyways :)

**Comment by z4kn4fein** [comment]
Hi @Kadajski 
A new version is available on my pre-release feed which possibly fixes this issue by generating a circular dependency check into every expression node, so they'll be evaluated by every call to the delegates. You can enable this feature by passing a `true` into the `WithCircularDependencyTracking()`. Could you please check that it solves your issue or not?
Thanks!

**Comment by BetterConfig** [comment]
Cool! Happy to hear that 👍

**Comment by z4kn4fein** [comment]
Cool! Happy to hear that 👍
