### ISSUE TITLE
Issue with Member Injection with Attribute but private setter

### ISSUE THREAD

**Issue by Nikey646** [z4kn4fein/stashbox#43]
I know that i can do Memeber Injection without an Attribute and a private setter, however due to wanting to use Unknown Type Resolution which in combination with Attributeless Member Injection won't work for me, due to third party dependencies (Tries to construct an object that uses Singleton pattern) I would prefer to stick with Attributes.

I want to avoid constructor injection for objects like Loggers that have a generic parameter for the current class, especially in abstract classes because this would result in child classes having to accept two loggers in the constructor. However to use Member Injection for these, it would require that both the property and setter be public and for my senario this doesn't make sense.

Is there anyway to have the default member injection have something similar to the `AutoMemberInjectionRules.PropertiesWithLimitedAccess` rule for Attributeless Injection?

Edit: It appears that my issue could also be related to the fact that the members i'm trying to have injected are on a base class? Does Stashbox support this senario?

Edit: Upon further inspection, the above edit does appear to be my issue. Member Injection does not seem to check base classes for any members that might need to be injected as well. So i guess this is now a feature request? Could base classes have members being injected as well?

**Comment by z4kn4fein** [comment]
Hi @Nikey646 

Yeah it seems that feature was missing, but i added it now, you can check it in the [latest pre-release package](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox).
Also added some [tests](https://github.com/z4kn4fein/stashbox/blob/master/src/stashbox.tests/IssueTests/43_Issue_with_Member_Injection_with_Attribute_but_private_setter.cs) to cover those cases. Let me know if you have further issues! 

Thanks!

**Comment by Nikey646** [comment]
Updated to the preview version, and it now works as i expected it to! Thanks~
