### ISSUE TITLE
Generate one instance for multiple interfaces

### ISSUE THREAD

**Issue by malibVB** [z4kn4fein/stashbox#50]
When I use `.AsImplementedTypes()`, it resolves a new instance of implemented-type for each service-type. Even though, if I use `.WithSingletonLifetime()` !

Is that correct ?

I had expected, that one instance will be created and can be resolved with each interface.

**Comment by z4kn4fein** [comment]
Hi, thanks for pointing out this, it seems you are right, a new registration is created for every implemented interface, that is why you got a new instance even when it's registered as a singleton. 

I'll fix this soon and publish it with the next release.

**Comment by malibVB** [comment]
Thank you, for your quick reply.
I'll wait for your fix.

**Comment by z4kn4fein** [comment]
Hey, i published a new version into my [pre-release](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox) nuget feed, which contains the fix, could you please check that it works as expected on your side also?

**Comment by malibVB** [comment]
Hey,

Good work, now it's working as expected.
Thank you very much for the quick fix.

**Comment by z4kn4fein** [comment]
Cool, i'll release it after some more test rounds in the next few days

**Comment by z4kn4fein** [comment]
released in [v2.7.1](https://github.com/z4kn4fein/stashbox/releases/tag/2.7.1)
