### ISSUE TITLE
[Feature Request] ComposeBy / ICompositionRoot with an instance and / or injection

### ISSUE THREAD

**Issue by 0x15e** [z4kn4fein/stashbox#53]
Currently when using ComposeBy, the class that implements ICompositionRoot is instantiated using System.Activator and it is not possible to easily pass parameters to the composition root.

A concept that I miss from StructureMap is the ability to use an instance of its Registry class (rather than just the registry class's type), so that it can be constructed with a few parameters before the container uses it to register anything.

It would be helpful if I had the ability to do either or both of these:

* Call ComposeBy with an already-instantiated object that implements ICompositionRoot.
* Allow the option of having Stashbox instantiate / buildup the composition root object(s) so that parameters / members can be injected into them.

**Comment by z4kn4fein** [comment]
Hey,
I think these are good features to have in Stashbox, I'll implement and publish them in the next release! Thanks!

**Comment by z4kn4fein** [comment]
I pushed a new version to my [release nuget feed](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox) which contains this feature, could you please check it out that it works as you expected? Thanks!

**Comment by 0x15e** [comment]
I had a look at the new features yesterday and all looks good. Thanks for the quick response!

**Comment by z4kn4fein** [comment]
released in [v2.7.4](https://github.com/z4kn4fein/stashbox/releases/tag/2.7.4)
