### ISSUE TITLE
how to implement castle dynamic proxy extension registration?

### ISSUE THREAD

**Issue by mehmtburak** [z4kn4fein/stashbox#60]
how to implement castle dynamic proxy extension registration?

**Comment by z4kn4fein** [comment]
Hey, 
[Here](https://github.com/z4kn4fein/stashbox/wiki/Decorators#interception) is some info in the docs about using a castle dynamic proxy as a decorator for your service registration. If you have more questions please let me know!

**Comment by mehmtburak** [comment]
Hey,
If I ignored why the subject of intercetion may be under the decorator title :)
Thanks for the quick response
