### ISSUE TITLE
intercep bug : why one request method but two calling intercep?

### ISSUE THREAD

**Issue by mehmtburak** [z4kn4fein/stashbox#61]
why one request method but two calling intercep?

**Comment by z4kn4fein** [comment]
Hey,
Could you please give me a bit more detail about what your actual issue is?

**Comment by mehmtburak** [comment]
My registration code

>             var dataAccessRegistrations =
>                 from type in dataAccessAssembly.GetExportedTypes()
>                 where type.FullName.EndsWith("Dal")
>                 from service in type.GetInterfaces()
>                 select new ImplementationTypes { service = service, implementation = type };
> 
>             container.Register<IInterceptor, MonitoringInterceptor>();
> 
>             foreach (var reg in dataAccessRegistrations)
>             {
>                 if (reg.implementation.IsClass)
>                 {
>                     Type serviceType = reg.service;
>                     var currentServiceProxy = ProxyBuilder.CreateInterfaceProxyTypeWithTargetInterface(serviceType, new Type[0], ProxyGenerationOptions.Default);
> 
>                     container.Register(reg.service, reg.implementation);
>                     container.RegisterDecorator(serviceType, currentServiceProxy);
>                 }
>             }

and my interceptor;

>         private class MonitoringInterceptor : IInterceptor
>         {
>             private readonly Dal.Abstract.ILogDal logger;
> 
>             public MonitoringInterceptor(Dal.Abstract.ILogDal logger)
>             {
>                 this.logger = logger;
>             }
> 
>             public void Intercept(IInvocation invocation)
>             {
>                 var watch = Stopwatch.StartNew();
> 
>                 invocation.Proceed();
> 
>                 var response = invocation.ReturnValue;
> 
>                 var decoratedType = invocation.InvocationTarget.GetType();
> 
>                 watch.Stop();
> 
>                 if (watch.Elapsed.TotalSeconds > 5)
>                 {
>                     string inputParameterModels =
>                         (invocation.Arguments != null && invocation.Arguments.Length > 0)
>                         ? JsonConvert.SerializeObject(invocation.Arguments)
>                         : string.Empty;
>                     this.logger.Create(
>                         new Entities.LogModels.SystemLog(
>                             Entities.LogModels.SystemLog.LogTypes.Performance,
>                             decoratedType.Name,
>                             string.Format("{0} executed in {1} ms. Arguments : {2}", decoratedType.Name, watch.ElapsedMilliseconds, inputParameterModels)
>                         )
>                     );
>                 }
>             }
>         }


then the intercept method works twice when I call any method. Do I need to provide more detailed information?

**Comment by mehmtburak** [comment]
additionally requesting from web api application

**Comment by z4kn4fein** [comment]
Thanks for the details, I'll check today what could be the problem!

**Comment by z4kn4fein** [comment]
Currently, I'm not able to reproduce this issue, could you please give me a bit more details?
What kind of types are there in that list you iterating over? Are there types that implementing more interfaces? Are the types mapped to the same service type? 
How does your actual intercepted service call look like? Are you sure you are not invoking it twice accidentally?

**Comment by mehmtburak** [comment]
I actually encountered this problem in a client's project so I can't send the code. However, because I was curious about the subject, I opened a zero project and tried it and I didn't encounter the same problem. But I know that I don't see this when I try on the simple injector with the same registration methodology. so I'm sure I didn't call twice.

However, I would like to point out that in fact, even though he interferes with the intercept method twice, he runs the method itself once in an interesting way. So this doesn't make it work as far as I've found, so it doesn't seem to be a vital bug

I think the ability to use proxies as decorators was a good idea.

thank you for your interest
if I have a new detection, I will write again

I wish you a good day

**Comment by z4kn4fein** [comment]
Ah, I see, thanks for the info anyway, if it's working correctly with simple injector then there's a good chance that there is something to improve inside the decorator implementation here. Please let me know if you find anything! Thanks!
