### ISSUE TITLE
ComposeBy with params doesn't work

### ISSUE THREAD

**Issue by AlekseiSmr** [z4kn4fein/stashbox#65]
Hi! I'm trying to pass my params into ComposeBy as compositionRootArguments and expect find this params in ctor of ICompositionRoot module, but it doesn't work. Please provide a good example on wiki or if it is a bug, I'd appreciate it if you could fix it.

Some screenshots:
![image](https://user-images.githubusercontent.com/25246926/65828487-66e44900-e2ac-11e9-9c24-d8561d1d0200.png)

and the result is:

![image](https://user-images.githubusercontent.com/25246926/65828506-972be780-e2ac-11e9-86ec-9659eb49d828.png)

**Comment by z4kn4fein** [comment]
Hey!

You don't have to use params argument for the composition root's constructor, you can simply declare it with your arguments like:
`public ApplicationDiModule(Dep1 dep1, Dep2 dep2)`

Let me know if you have further issues or questions!

**Comment by AlekseiSmr** [comment]
Hey!

Thank you, it works :) On my opinion, it would be cool to put example under Composition wiki page

**Comment by z4kn4fein** [comment]
Sure thing, I'll do it!
