### ISSUE TITLE
Possibility of WCF Extension? (enhancement/question)

### ISSUE THREAD

**Issue by devworker55** [z4kn4fein/stashbox#7]
Good Day,

I've been following up and coming IoC containers, one of w for a while now; this led me is yours and I was curious if you had any plans on creating a "stashbox" extension for the wcf service platform. I have sufficient experience in "IoC" concepts and would be willing to start the groundwork for such an endeavor if you're interested. 

Either way, I've been very impressed by the work you've done with stashbox over the last couple months, here's hoping it gets some traction within the foreseeable future.

**Comment by z4kn4fein** [comment]
Hey!

Thanks for the feedback, sure, i'm very interested and would be very happy to see and help with the creation of the extension you mentioned. Feel free to start working on it and contact me if you'd have any questions or need some support!

**Comment by devworker55** [comment]
Hi,

So I began worked on the extension this past weekend and have made a fair amount of progress, however I was exploring an approach by which I would attempt to get the registration info of the registered WCF service type from the container but I am having a bit of trouble.

**Goal**: Determine if service is registered as singleton or not so as to perform certain validation checks since we do not have full control of service instance through WCF pipeline,

**Info Required**: Lifestyle configuration if any, TypeInformation (not required but helpful).

**Retrieval Via**: ServiceType.

Would you be able to assist me on the best approach to retrieve the above information? 

Thanks!

**Comment by devworker55** [comment]
Also, is container.CanResolved(Type serviceType) equivalent to other IoC containers "container.IsRegistered(Type serviceType)" ? If not, what should I use to gather that information?

**Comment by z4kn4fein** [comment]
Hi,

Thanks, i'm very happy to hear that you are started to work on the WCF extension. :)

The `CanResolve` will only tell you whether a service type  can be resolved by the container or not, even if the given type itself isn't registered into the container, but any of the resolvers are capable to resolve it. I mean it'll say true if you ask with some kind of wrapped type like `IEnumerable` or something else which can be handled by the container.

In the meantime, regarding to your request i moved some registration state information to public scope, so the info you need now can be grabbed by reading from the RegistrationRepository e.g.:

```c#
 var reg = container.ContainerContext.RegistrationRepository.GetAllRegistrations().FirstOrDefault(r => r.ServiceType /* or you can check the implementation type as well by writing r.ImplementationType */ == typeof(IService));
```

This will return an `IServiceRegistration` for you which contains the `Lifetime` as well, please check that there is enough info for you and please let me know if you need more. It's under the *Infrastructure/Registration* folder.

The changes i mentioned only available on my preview nuget feed (https://www.myget.org/F/pcsajtai/api/v3/index.json or https://www.myget.org/F/pcsajtai/api/v2) yet, i'm planning to create a new release soon which will contain them also but first i'd like to finish my current tasks.

I'm currently working on the *refactor* branch so you can check the interface there, and if you'd like feel free to open new branches, the ci process will push preview packages from them to that nuget feed as well.

Thanks!

**Comment by devworker55** [comment]
Hi,

Thank you for the detailed response, I went ahead and looked at the updates to IServiceRegistration that you mentioned and it indeed has all the information I need. Thank you!

So I believe I'm mostly complete with the extension, just waiting for your latest changes to be pushed to the official nuget feed so I can include it as part of the extension.

When you get a moment could you create an empty repository under your account named 
"stashbox-extension-wcf". Once you do, I'll branch it and push the implementation I have and create a pull request for you to review.

Also, I don't have any experience with appveyor and very little with setting up a nuget package so most likely I'll be requiring your assistance with those.

Thanks again.

**Comment by z4kn4fein** [comment]
Hi,

Sure, i pushed the new version yesterdey to nuget.org so probably you are now able to use it.

I think that project belongs to you more than me, so what do you think about creating your own repository and i would be happy to join to it as a contributor, and help with the appveyor configuration and nuget generation, which i think also belongs to you so if you'd like, you can create your own account for them as well. Appveyor supports the authentication with github credentials and nuget.org supports microsoft live account, so you don't have to create really new accounts but use existing ones.

What do you think about this approach?

In the meantime i also created a stashbox slack team for easier communication about the project, if you think i can send you an invitation.

Thanks!

**Comment by devworker55** [comment]
Hi,

If you're ok with that approach then I am honored to host and maintain the extension. I went ahead and created both appveyor and nuget.org accounts so that they have available when we get a chance to configure the builds and nuget feeds. Also, yes you can send an invitation for the stashbox slack team
to "abj.developer@gmail.com". Thanks.

I've added you as a collaborator to the project, for the remainder of the week I'll be working on the unit tests and setting up a sample project to demonstration configuration options.

My apologies for the late reply, this past weekend was a bit busy. Oddly enough I tend to have more time during the week than on the weekends, go figure.

**Comment by devworker55** [comment]
Closing and continuing discussion on Stashbox slack team.
