### ISSUE TITLE
How to set default lifetime for registered services & instances?

### ISSUE THREAD

**Issue by brianjlacy** [z4kn4fein/stashbox#72]
I don't want to have to say "RegisterSingleton" or use the "WithLifetime(new SingletonLifetime())" method every time I register a service. Is there a way to set the default lifetime scope for all registrations, so I can override specifically when I need e.g. Transient?

**Comment by z4kn4fein** [comment]
Currently, it's not possible, however, it's very easy to implement, so I'll do it soon! Thanks for the request!

**Comment by z4kn4fein** [comment]
Hey, this functionality is now available on my latest [pre-release package](https://www.myget.org/feed/pcsajtai/package/nuget/Stashbox), could you please try it, that it works as you expected?

**Usage**:
`new StashboxContainer(config => config.WithDefaultLifetime(new ScopedLifetime()))`

**Comment by brianjlacy** [comment]
@z4kn4fein Haven't had a chance to try it out yet, but I super appreciate the quick turnaround!

**Comment by schuettecarsten** [comment]
I wonder about `new ScopedLifetime()` in the sample. Is this really neccessary and useful? It will create a new instance every time...

**Comment by z4kn4fein** [comment]
Yep, that's fine, it'll create a new one for every registration because every registration uses its own lifetime

**Comment by z4kn4fein** [comment]
released in [v2.8.7](https://github.com/z4kn4fein/stashbox/releases/tag/2.8.7)
