### ISSUE TITLE
Register Assemblies

### ISSUE THREAD

**Issue by vector-man** [z4kn4fein/stashbox#8]
Is there a way to register various assemblies containing registrations?

**Comment by z4kn4fein** [comment]
Hi!

It's not supported yet, but i'm planning to add this feature in the next release, do you have any concrete needs it should fulfill?

**Comment by vector-man** [comment]
Hi, thanks for the reply. I just have a main assembly that I need to register two other assemblies from.

    private static void Main(){
        // Register assembly A
        // Register assembly B.
        // Resolve
    }

**Comment by z4kn4fein** [comment]
Hey, i added this feature right now, can you confirm that it works as you expected? You can try it via the latest beta package from here: https://www.myget.org/F/pcsajtai/api/v2

Sample:
```c#
container.RegisterAssembly(assembly);
//or
container.RegisterAssemblyContaining<Foo>();
//or
container.RegisterAssemblies(new[] { assembly1, assembly2 });
```

**Comment by vector-man** [comment]
Thanks. I'll test it out soon. I'm migrating from Autofac, so it may take a day or so :).

**Comment by vector-man** [comment]
I don't see a regular version at that source, just ones for ASP.NET.

**Comment by z4kn4fein** [comment]
Ah sry, i forgot to mention, it's a prerelease package, you'll be able to see it if you check the 'Include prerelease' checkbox in the nuget pkg manager. :)

**Comment by vector-man** [comment]
I'm not quite sure how this will work. Any help is appreciated. I have an assembly with this class:

    public class CommonBoostrapper
    {
        public void Bootstrap()
        {
         // How to register in here?
        }
    }

Main assembly:

          private static void Main()
          {
            ...
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(
            container.RegisterAssemblyContaining<CommonBoostrapper>();   
            ....
        }

**Comment by z4kn4fein** [comment]
Hey, in this case all the publicly visible classes in the assembly of the CommonBoostrapper will be registered into the container by their implemented interfaces, if it's not enough, could you explain a bit what do you need more? Thanks!

**Comment by vector-man** [comment]
I basically need something like LightInject (under the Assembly Scanning/ Composition Root section): https://github.com/seesharper/LightInject

**Comment by z4kn4fein** [comment]
Ah i see, sry, it wasn't clear for me, i'm going to implement that type of registration in the next few days as well. :)
Thanks for pointing this out and the clarification!

**Comment by vector-man** [comment]
Thank you :). Oh, and the ability to access the main container from within the other assemblies during registration would be nice :).

**Comment by z4kn4fein** [comment]
Hey, i updated the latest beta package with the composing solution, you can try it like this:
```c#
public class CommonBoostrapper : ICompositionRoot
{
    public void Compose(IStashboxContainer container)
    {
     // Register here
    }
}


container.ComposeBy<CommonBoostrapper>();

//You can also pass your assembly which contains ICompositionRoot implementations:

container.ComposeAssembly(assembly)
```

Thanks!

**Comment by z4kn4fein** [comment]
Added in [2.4.1](https://github.com/z4kn4fein/stashbox/releases/tag/2.4.1)
