### ISSUE TITLE
Register Async Func

### ISSUE THREAD

**Issue by vector-man** [z4kn4fein/stashbox#9]
Hi. I'm trying to register something like this. Is it possible?

    container.RegisterInstance<Func<string, Task<IValidator<string>>>>(async (schema) => await container.Resolve<ISchemaValidatorFactory>().FromFileAsync(schema));

Edit: It also looks like registering Func factories with parameters are not supported?

**Comment by z4kn4fein** [comment]
Hi! No, it's not possible, only factories which will be evaluated inside the container are implemented yet, but i can add the support for those which are producing `Func<>` delegates, what do you think about if it could be accomplished like this: 
```C#
container.RegisterFunc<string, Task<IValidator<string>>>(async (schema, resolver) => await resolver.Resolve<ISchemaValidatorFactory>().FromFileAsync(schema));

//Then it can be resolved or injected as dependency like this:

var func = container.Resolve<Func<string, Task<IValidator<string>>>>();
```

**Comment by vector-man** [comment]
Sure, thanks fine. Thanks!

**Comment by z4kn4fein** [comment]
Yeah, i only implemented the parameterless and the one container parameter factory registration yet, more parameters are on the way :)

**Comment by z4kn4fein** [comment]
Hey, i fixed the instance registration which allows now what you mentioned, but i also added the support of the factory registration via the `RegisterFunc<>` method as i mentioned before, it aslo supports more function parameters. Could you please try it it's ok or should i add some more functionality to it? It's available in the latest beta package.
Thanks!

**Comment by z4kn4fein** [comment]
Added in [2.4.1](https://github.com/z4kn4fein/stashbox/releases/tag/2.4.1)
