### ISSUE TITLE
Use license expression in nuget package

### ISSUE THREAD

**Issue by publee** [z4kn4fein/stashbox#95]
Hi,

[NexusIQ](https://www.sonatype.com/nexus/iqserver) is not allowing me to download nuget package in the company. Probably doesn't understantd license type file.

Can you please change it to expression:

`<license type="expression">MIT</license>`

https://docs.microsoft.com/en-us/nuget/reference/nuspec#license

Thank you.

**Comment by z4kn4fein** [comment]
Hi, 
Yep, I already thought about to do so. I'm going to change it.

**Comment by z4kn4fein** [comment]
It's in the latest release

**Comment by publee** [comment]
Works, Thank you.
